### ISSUE TITLE
error with coffeescript

### ISSUE THREAD

**Issue by saeidalidadi** [hapijs/hapi-auth-cookie#131]
I wrote the example code in coffescript and gave me this error:
```
Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot read property 'account' of null
  at /home/SAlidadi/Projects/Learning/lesson10/index.coffee:72:26
  at /home/SAlidadi/Projects/Learning/lesson10/node_modules/hapi/node_modules/catbox/node_modules/hoek/lib/index.js:850:22
  at doNTCallback0 (node.js:407:9)
  at process._tickDomainCallback (node.js:377:13)
```

**Comment by Marsup** [comment]
The stack trace is pointing at your code, unlikely it's this module's fault.

**Comment by mtharrison** [comment]
Can you show your code?

**Comment by saeidalidadi** [comment]
This is my code:
```
  1 Hapi = require "hapi"
  2 
  3 uuid = 1;       # Use seq instead of proper unique identifiers for demo only
  4 
  5 users =
  6   john:
  7     id: 'john',
  8     password: 'password',
  9     name: 'John Doe'
 10 
 11 home = (request, reply) ->
 12   reply('<html><head><title>Login page</title></head><body><h3>Welcome ' +
 13         request.auth.credentials.name +
 14         '!</h3><br/><form method="get" action="/logout">' +
 15         '<input type="submit" value="Logout">' +
 16         '</form></body></html>'
 17   )
 18 
 19 login = (request, reply) ->
 20   if request.auth.isAuthenticated
 21     reply.redirect '/'
 22   message = ''
 23   account = null
 24   if request.method is 'post'
 25     if !request.payload.username or !request.payload.password
 26       message = 'Missing username or password'
 27     else
 28       account = users[request.payload.username]
 29       if !account or account.password isnt request.payload.password
 30         message = 'Invalid username or password'
 31   if request.method is 'get' or message
 32     reply('<html><head><title>Login page</title></head><body>' +
 33           (message ? '<h3>' + message + '</h3><br/>' : '') +
 34           '<form method="post" action="/login">' +
 35           'Username: <input type="text" name="username"><br>' +
 36           'Password: <input type="password" name="password"><br/>' +
 37           '<input type="submit" value="Login"></form></body></html>'
 38     )
 39 
 40   sid = String ++uuid
 41   request.server.app.cache.set sid, { account: account }, 0, (err) ->
 42     if err
 43       reply err
 44     request.cookieAuth.set { sid: sid }
 45     reply.redirect '/'
 46 
 47 logout = (request, reply) ->
 48   request.cookieAuth.clear()
 49   reply.redirect('/')
 50 
 51 server = new Hapi.Server()
 52 server.connection { port: 8000 }
 53 
 54 server.register(require('hapi-auth-cookie'), (err) ->
 55   if err
 56     throw err
 57 
 58   cache = server.cache { segment: 'sessions', expiresIn: 1000*10 }
 59   server.app.cache = cache
 60 
 61   server.auth.strategy('session', 'cookie', true, {
 62     password: 'password-should-be-32-characters'
 63     cookie: 'sid-example'
 64     redirectTo: '/login'
 65     isSecure: false
 66     validateFunc: (request, session, cb) ->
 67       cache.get(session.sid, (err, cached) ->
 68         if err
 69           cb err, false
 70         if !cached
 71           cb null, false
 72         cb null, true, cached.account
 73       )
 74   })
 75   server.route([{
 76     path: '/'
 77     method: 'GET'
 78     config:
 79       handler: home
 80   }
 81   ,
 82   {
 83     path: '/login'
 84     method: ['GET', 'POST']
 85     config:
 86       handler: login
 87       auth: { mode: 'try' }
 88       plugins: { 'hapi-auth-cookie' : { redirectTo: false } }
 89   }
 90   ,
 91   {
 92     path: '/logout'
 93     method: 'GET'
 94     config:
 95       handler: logout
 96   }])
 97   server.start (err) ->
 98     console.log("started")
 99 )

**Comment by Marsup** [comment]
It shouldn't even reach L72 considering L70, something's wrong in the coffee world :)

**Comment by mtharrison** [comment]
Without the line numbers:

```coffee
Hapi = require "hapi"

uuid = 1;       # Use seq instead of proper unique identifiers for demo only

users =
  john:
    id: 'john',
    password: 'password',
    name: 'John Doe'
 
 home = (request, reply) ->
   reply('<html><head><title>Login page</title></head><body><h3>Welcome ' +
         request.auth.credentials.name +
         '!</h3><br/><form method="get" action="/logout">' +
         '<input type="submit" value="Logout">' +
         '</form></body></html>'
   )
 
 login = (request, reply) ->
   if request.auth.isAuthenticated
     reply.redirect '/'
   message = ''
   account = null
   if request.method is 'post'
     if !request.payload.username or !request.payload.password
       message = 'Missing username or password'
     else
       account = users[request.payload.username]
       if !account or account.password isnt request.payload.password
         message = 'Invalid username or password'
   if request.method is 'get' or message
     reply('<html><head><title>Login page</title></head><body>' +
           (message ? '<h3>' + message + '</h3><br/>' : '') +
           '<form method="post" action="/login">' +
           'Username: <input type="text" name="username"><br>' +
           'Password: <input type="password" name="password"><br/>' +
           '<input type="submit" value="Login"></form></body></html>'
     )
 
   sid = String ++uuid
   request.server.app.cache.set sid, { account: account }, 0, (err) ->
     if err
       reply err
     request.cookieAuth.set { sid: sid }
     reply.redirect '/'
 
 logout = (request, reply) ->
   request.cookieAuth.clear()
   reply.redirect('/')
 
 server = new Hapi.Server()
 server.connection { port: 8000 }
 
 server.register(require('hapi-auth-cookie'), (err) ->
   if err
     throw err
 
   cache = server.cache { segment: 'sessions', expiresIn: 1000*10 }
   server.app.cache = cache
 
   server.auth.strategy('session', 'cookie', true, {
     password: 'password-should-be-32-characters'
     cookie: 'sid-example'
     redirectTo: '/login'
     isSecure: false
     validateFunc: (request, session, cb) ->
       cache.get(session.sid, (err, cached) ->
         if err
           cb err, false
         if !cached
           cb null, false
         cb null, true, cached.account
       )
   })
   server.route([{
     path: '/'
     method: 'GET'
     config:
       handler: home
   }
   ,
   {
     path: '/login'
     method: ['GET', 'POST']
     config:
       handler: login
       auth: { mode: 'try' }
       plugins: { 'hapi-auth-cookie' : { redirectTo: false } }
   }
   ,
   {
     path: '/logout'
     method: 'GET'
     config:
       handler: logout
   }])
   server.start (err) ->
     console.log("started")
 )

**Comment by saeidalidadi** [comment]
This is compiled code as JS:
```
// Generated by CoffeeScript 1.10.0
(function() {
  var Hapi, home, login, logout, server, users, uuid;

  Hapi = require("hapi");

  uuid = 1;

  users = {
    john: {
      id: 'john',
      password: 'password',
      name: 'John Doe'
    }
  };

  home = function(request, reply) {
    return reply('<html><head><title>Login page</title></head><body><h3>Welcome ' + request.auth.credentials.name + '!</h3><br/><form method="get" action="/logout">' + '<input type="submit" value="Logout">' + '</form></body></html>');
  };

  login = function(request, reply) {
    var account, message, sid;
    if (request.auth.isAuthenticated) {
      reply.redirect('/');
    }
    message = '';
    account = null;
    if (request.method === 'post') {
      if (!request.payload.username || !request.payload.password) {
        message = 'Missing username or password';
      } else {
        account = users[request.payload.username];
        if (!account || account.password !== request.payload.password) {
          message = 'Invalid username or password';
        }
      }
    }
    if (request.method === 'get' || message) {
      reply('<html><head><title>Login page</title></head><body>' + (message != null ? message : '<h3>' + message + {
        '</h3><br/>': ''
      }) + '<form method="post" action="/login">' + 'Username: <input type="text" name="username"><br>' + 'Password: <input type="password" name="password"><br/>' + '<input type="submit" value="Login"></form></body></html>');
    }
    sid = String(++uuid);
    return request.server.app.cache.set(sid, {
      account: account
    }, 0, function(err) {
      if (err) {
        reply(err);
      }
      request.cookieAuth.set({
        sid: sid
      });
      return reply.redirect('/');
    });
  };

  logout = function(request, reply) {
    request.cookieAuth.clear();
    return reply.redirect('/');
  };

  server = new Hapi.Server();

  server.connection({
    port: 8000
  });

  server.register(require('hapi-auth-cookie'), function(err) {
    var cache;
    if (err) {
      throw err;
    }
    cache = server.cache({
      segment: 'sessions',
      expiresIn: 1000 * 10
    });
    server.app.cache = cache;
    server.auth.strategy('session', 'cookie', true, {
      password: 'password-should-be-32-characters',
      cookie: 'sid-example',
      redirectTo: '/login',
      isSecure: false,
      validateFunc: function(request, session, cb) {
        return cache.get(session.sid, function(err, cached) {
          if (err) {
            cb(err, false);
          }
          if (!cached) {
            cb(null, false);
          }
          return cb(null, true, cached.account);
        });
      }
    });
    server.route([
      {
        path: '/',
        method: 'GET',
        config: {
          handler: home
        }
      }, {
        path: '/login',
        method: ['GET', 'POST'],
        config: {
          handler: login,
          auth: {
            mode: 'try'
          },
          plugins: {
            'hapi-auth-cookie': {
              redirectTo: false
            }
          }
        }
      }, {
        path: '/logout',
        method: 'GET',
        config: {
          handler: logout
        }
      }
    ]);
    return server.start(function(err) {
      return console.log("started");
    });
  });

}).call(this);
```

**Comment by mtharrison** [comment]
For a start you're missing several important return statements. e.g.:

```js
if (request.auth.isAuthenticated) {
    reply.redirect('/');
}
```

This is incorrect because you wouldn't want to continue executing after the redirect. I think something has been lost in the translation to coffee.

**Comment by saeidalidadi** [comment]
I tested @mtharrison idea, also the pre result :+1:

**Comment by saeidalidadi** [comment]
@mtharrison and @Marsup the error solved :+1: 
Need a return
```javascript
    validateFunc: (request, session, cb) ->
       cache.get(session.sid, (err, cached) ->
         if err
           return cb err, false
         if !cached
           cb null, false
         cb null, true, cached.account
```
